model:
  rng_seed: 42
  model_type: 'global_univariate_lstm'
  model_config:
    hyperparameter_tuning_range:
      hidden_size: [1, 100]
      number_of_layers: [1, 2]
      dropout: [0.0, 0.4]
      recurrent_dropout: [0.0, 0.4]
      #optimizer_name: ['Adam', 'RMSprop']
      optimizer_name: ['RMSprop', 'Adam']
      #optimizer_name: ['Adam']
      learning_rate: [1e-7, 1e-2]
      number_of_epochs: [1, 40]
      batch_size: [32, 32]
      input_window_size: 10
      output_window_size: 7 # must be equal output_window_size
      multi_variable_nr: 1 # must be equal to number of variables used in multi variable (1 if uni variate)
      number_of_features: 1 # must be equal to number of features in data
      number_of_trials: 400 # Number of tuning trials to run. The more the better.
      #time_to_tune_in_minutes: 6000  # Time to tune in minutes, If both number of trials or time to tune is set, first one to finnish.
      stateful_lstm: true

    global_model:
      model_structure:
        training_size: 50
        input_window_size: 10
        output_window_size: 7
        multi_variable_nr: 4
        batch_size: 32
        number_of_epochs: 15
        stateful_lstm: yes
        should_shuffle_batches: no
        optimizer_name: Adam
        learning_rate: 0.0016146453106769651
        number_of_features: 1
        layers:
          [
            {
              hidden_size: 62,
              dropout: 3.4171700927954074e-05,
              recurrent_dropout: 0.3563995834345084
            },
            
          ]
      datasets:
        # - 11573
        # - 11037
        - 77
        - 79
        - 11217
        - 11334
        - 11992
        - 12265
        - 12511



    local_model:
      common_parameters_for_all_models:
        # If int <= 1 then the testing set will be equal to output_window_size
        #training_size: 50 # Number of samles in validation set
        input_window_size: 10
        output_window_size: 7
        multi_variable_nr: 1
        batch_size: 32
        stateful_lstm: yes
        should_shuffle_batches: no
        number_of_features: 1

      model_structure:

        - time_series_id: 77
          number_of_epochs: 15
          optimizer_name: Adam
          learning_rate: 0.00028345282219663603
          hidden_layer_size: 60
          dropout: 0.24970090559798974
          number_of_features: 1
          layers:
            - hidden_size: 94
              dropout: 0.21199
              recurrent_dropout: 0.0
        - time_series_id: 79
          number_of_epochs: 15
          optimizer_name: Adam
          learning_rate: 0.00028345282219663603
          hidden_layer_size: 60
          dropout: 0.24970090559798974
          number_of_features: 1
          layers:
            - hidden_size: 94
              dropout: 0.21199
              recurrent_dropout: 0.0
        - time_series_id: 11217
          number_of_epochs: 15
          optimizer_name: Adam
          learning_rate: 0.00028345282219663603
          hidden_layer_size: 60
          dropout: 0.24970090559798974
          number_of_features: 1
          layers:
            - hidden_size: 94
              dropout: 0.21199
              recurrent_dropout: 0.0
        - time_series_id: 11334
          number_of_epochs: 15
          optimizer_name: Adam
          learning_rate: 0.00028345282219663603
          hidden_layer_size: 60
          dropout: 0.24970090559798974
          number_of_features: 1
          layers:
            - hidden_size: 94
              dropout: 0.21199
              recurrent_dropout: 0.0
        - time_series_id: 11992
          number_of_epochs: 15
          optimizer_name: Adam
          learning_rate: 0.00028345282219663603
          hidden_layer_size: 60
          dropout: 0.24970090559798974
          number_of_features: 1
          layers:
            - hidden_size: 94
              dropout: 0.21199
              recurrent_dropout: 0.0
        - time_series_id: 12265
          number_of_epochs: 15
          optimizer_name: Adam
          learning_rate: 0.00028345282219663603
          hidden_layer_size: 60
          dropout: 0.24970090559798974
          number_of_features: 1
          layers:
            - hidden_size: 94
              dropout: 0.21199
              recurrent_dropout: 0.0
        - time_series_id: 12511
          number_of_epochs: 15
          optimizer_name: Adam
          learning_rate: 0.00028345282219663603
          hidden_layer_size: 60
          dropout: 0.24970090559798974
          number_of_features: 1
          layers:
            - hidden_size: 94
              dropout: 0.21199
              recurrent_dropout: 0.0