model:
  rng_seed: 42
  model_type: 'local_univariate_lstm'
  model_config:
    hyperparameter_tuning_range:
      hidden_size: [1, 100]
      number_of_layers: [1, 2]
      dropout: [0.0, 0.4]
      recurrent_dropout: [0.0, 0.4]
      #optimizer_name: ['Adam', 'RMSprop']
      optimizer_name: ['RMSprop', 'Adam']
      #optimizer_name: ['Adam']
      learning_rate: [1e-7, 1e-2]
      number_of_epochs: [1, 40]
      batch_size: [32, 32]
      input_window_size: 10
      output_window_size: 7 # must be equal output_window_size
      multi_variable_nr: 1 # must be equal to number of variables used in multi variable (1 if uni variate)
      number_of_features: 1 # must be equal to number of features in data
      number_of_trials: 200 # Number of tuning trials to run. The more the better.
      #time_to_tune_in_minutes: 6000  # Time to tune in minutes, If both number of trials or time to tune is set, first one to finnish.
      stateful_lstm: true

    global_model:
      model_structure:
        input_window_size: 10
        output_window_size: 7
        multi_variable_nr: 4
        batch_size: 32
        number_of_epochs: 40
        stateful_lstm: yes
        should_shuffle_batches: no
        optimizer_name: RMSprop
        learning_rate: 0.0010480378531841522
        number_of_features: 1
        layers:
          [
            {
              hidden_size: 97,
              dropout: 0.07577543324992782,
              recurrent_dropout: 0.3860940444331956,
            },
            {
              hidden_size: 41,
              dropout: 0.23565282953964958,
              recurrent_dropout: 0.05715033086301391,
            },
          ]
      datasets:
        - 2
        - 6
        - 9
        - 10
        - 11
        - 13
        - 20

    local_model:
      common_parameters_for_all_models:
        # If int <= 1 then the testing set will be equal to output_window_size
        #training_size: 50 # Number of samles in validation set
        input_window_size: 10
        output_window_size: 7
        multi_variable_nr: 1
        batch_size: 32
        stateful_lstm: yes
        should_shuffle_batches: no
        number_of_features: 1

      model_structure:
        - time_series_id: 2
          number_of_epochs: 20
          optimizer_name: RMSprop
          learning_rate: 0.000123319
          number_of_features: 1
          layers:
            - hidden_size: 84
              dropout: 0.011609
              recurrent_dropout: 0.145647
            - hidden_size: 94
              dropout: 0.20344
              recurrent_dropout: 0.3804909

        - time_series_id: 6
          number_of_epochs: 29
          optimizer_name: RMSprop
          learning_rate: 0.0004707068
          number_of_features: 1
          layers:
            - hidden_size: 39
              dropout: 0.3368706
              recurrent_dropout: 0.2348005

        - time_series_id: 9
          number_of_epochs: 16
          optimizer_name: RMSprop
          learning_rate: 0.000840387298
          number_of_features: 1
          layers:
            - hidden_size: 24
              dropout: 0.00062984
              recurrent_dropout: 0.3757795967

        - time_series_id: 10
          number_of_epochs: 4
          optimizer_name: RMSprop
          learning_rate: 0.001474852
          number_of_features: 1
          layers:
            - hidden_size: 80
              dropout: 0.253187256787
              recurrent_dropout: 0.3752092266

        - time_series_id: 11
          number_of_epochs: 3
          optimizer_name: RMSprop
          learning_rate: 0.0033873287
          number_of_features: 1
          layers:
            - hidden_size: 15
              dropout: 0.06573998
              recurrent_dropout: 0.133365756

        - time_series_id: 13
          number_of_epochs: 16
          optimizer_name: Adam
          learning_rate: 0.000409735
          number_of_features: 1
          layers:
            - hidden_size: 85
              dropout: 0.019903239
              recurrent_dropout: 0.14670325

        - time_series_id: 20
          number_of_epochs: 22
          optimizer_name: RMSprop
          learning_rate: 0.00617737261855
          number_of_features: 1
          layers:
            - hidden_size: 3
              dropout: 0.0179576858
              recurrent_dropout: 0.080991248985
