model:
  rng_seed: 42
  model_type: 'global_univariate_cnn_ae_lstm'
  model_config:
    hyperparameter_tuning_range:
      hidden_size: [ 1, 100 ]
      number_of_layers: [ 1, 2 ]
      dropout: [ 0.0, 0.4 ]
      recurrent_dropout: [0.0, 0.4]
      optimizer_name: [ 'RMSprop', 'Adam' ]
      learning_rate: [ 1e-7, 1e-2 ]
      number_of_epochs: [ 1, 40 ]
      batch_size: [ 32, 32 ]
      input_window_size: 10
      output_window_size: 7 # must be equal output_window_size
      multi_variable_nr: 1 # must be equal to number of variables used in multi variable (1 if uni variate)
      number_of_features: 1 # must be equal to number of features in data
      number_of_trials: 200 # Number of tuning trials to run. The more the better.
      #time_to_tune_in_minutes: 6000  # Time to tune in minutes, If both number of trials or time to tune is set, first one to finnish.
      stateful_lstm: true
    common_parameters_for_all_models:
      should_shuffle_batches: False
      batch_size: 32
      input_window_size: 10
      output_window_size: 7
      multi_variable_nr: 4
      lstm-shared:
        input_window_size: 10
        output_window_size: 7
        multi_variable_nr: 4
      lstm:
        optimizer_name: 'RMSprop'
        stateful_lstm: True
        loss: "mae"
        learning_rate: 0.0055650427474727825
        number_of_features: 4
        epochs: 11
        layers:
          - hidden_size: 20
            dropout: 0.020082865622793683
            recurrent_dropout: 0.3242390476860587
      ae:
        optimizer_name: 'Adam'
        loss: "mae"
        learning_rate: 0.0001
        epochs: 70
      encoder:
        - layer: "Conv1d"
          filters: 16
          kernel_size: 3
          activation: "relu"
        - layer: "Conv1d"
          filters: 32
          kernel_size: 5
          activation: "relu"
      decoder:
        - layer: "Conv1dTranspose"
          kernel_size: 5
          filters: 32
          activation: "relu"
        - layer: "Conv1dTranspose"
          kernel_size: 3
          filters: 4

    model_structure:
      - 2
      - 6
      - 9
      - 10
      - 11
      - 13
      - 20
      - 22
      - 24
      - 26
      - 27
      - 28
      - 29
      - 32
      - 33
      - 34
      - 39
      - 41
      - 51
      - 54
